### ISSUE TITLE
Crash when using KeyValue.loadAsText() with local appinfo file. 

### ISSUE THREAD

**Issue by LossyDragon** [Longi94/JavaSteam#215]
### Expected Behavior
Should be able to parse a local appinfo vdf text file into KeyValues. 

### Actual Behavior
This is probably due to the local file not being read with UTF-8 encoding. 

```
Exception in thread "main" java.lang.NullPointerException: Cannot invoke "String.startsWith(String)" because "s" is null
	at in.dragonbra.javasteam.types.KVTextReader.<init>(KVTextReader.java:59)
	at in.dragonbra.javasteam.types.KeyValue.readAsText(KeyValue.java:357)
	at in.dragonbra.javasteam.types.KeyValue.loadFromFile(KeyValue.java:452)
	at in.dragonbra.javasteam.types.KeyValue.loadAsText(KeyValue.java:424)
	at in.dragonbra.javasteamsamples._4friends.TestKV.main(TestKV.java:12)
```

### Steps to Reproduce the Problem

  1. Call SteamApps.picsGetProductInfo() with metadata `true`
  2. Locally download the .gz file and extract the text file
  3. Call method `KeyValue.loadAsText()`

### Specifications

  - Version: 1.1.0
  - Platform: Windows

**Comment by LossyDragon** [comment]
Sample App
```
public class TestKV {

    public static void main(String[] args) {
        KeyValue kv = new KeyValue();

        // AppID: 1938090
        // http://clientconfig.akamai.steamstatic.com/appinfo/1938090/sha/<App's_SHA>.txt.gz
        KeyValue.loadAsText("....");

        printKeyValue(kv, 1);
    }

    private static void printKeyValue(KeyValue keyValue, int depth) {
        if (keyValue.getChildren().size() == 0) {
            System.out.println(keyValue.getName() + ": " + keyValue.getValue());
        } else {
            System.out.println(keyValue.getName() + ":");
            for (KeyValue child : keyValue.getChildren()) {
                printKeyValue(child, depth + 1);
            }
        }
    }
}
```
