### ISSUE TITLE
Timeout error: steamClient.connect();

### ISSUE THREAD

**Issue by exellian** [Longi94/JavaSteam#4]
### Expected Behavior
`steamClient.connect();`
Should work every time
### Actual Behavior
the reconnecting advise didn't work for me. I have to delete the servers.bin file every time before i start the program.
I also tried to call the disconnect function, probably there is a cleanup or so, but that also didnt work
### Steps to Reproduce the Problem

  1. connect
  2. end the program
  3. start it again -> timeout error
  4. delete servers.bin -> No timeout error

### Specifications

  - Version: javasteam-1.0.0-20180311.021716-6
  - Platform: Windows 10

### console-output:
```[bot#0] Connecting...

09:55:38.647 [  Thread-0] in.dragonbra.javasteam.steam.discovery.SmartCMServerList - Resolving server list

09:55:39.329 [  Thread-0] in.dragonbra.javasteam.steam.discovery.SmartCMServerList - Resolved 160 servers

09:55:39.348 [  Thread-0] in.dragonbra.javasteam.networking.steam3.TcpConnection - Connecting to /40.197.254.162:27019...

09:55:44.350 [  Thread-0] in.dragonbra.javasteam.networking.steam3.TcpConnection - Socket exception while completing connection request to /40.197.254.162:27019

java.net.SocketTimeoutException: connect timed out

09:55:44.353 [  Thread-0] 	at java.net.DualStackPlainSocketImpl.waitForConnect(Native Method)

	at java.net.DualStackPlainSocketImpl.socketConnect(Unknown Source)

	at java.net.AbstractPlainSocketImpl.doConnect(Unknown Source)

	at java.net.AbstractPlainSocketImpl.connectToAddress(Unknown Source)

	at java.net.AbstractPlainSocketImpl.connect(Unknown Source)

	at java.net.PlainSocketImpl.connect(Unknown Source)

	at java.net.SocksSocketImpl.connect(Unknown Source)

	at java.net.Socket.connect(Unknown Source)

	at in.dragonbra.javasteam.networking.steam3.TcpConnection.connect(TcpConnection.java:114)

	at in.dragonbra.javasteam.networking.steam3.EnvelopeEncryptedConnection.connect(EnvelopeEncryptedConnection.java:193)

	at in.dragonbra.javasteam.networking.steam3.Connection.connect(Connection.java:62)

	at in.dragonbra.javasteam.steam.CMClient.connect(CMClient.java:166)

	at in.dragonbra.javasteam.steam.CMClient.connect(CMClient.java:137)

	at steam.SteamUser.run(SteamUser.java:113)

	at java.lang.Thread.run(Unknown Source)

in.dragonbra.javasteam.networking.steam3.TcpConnection - Timed out while connecting to /40.197.254.162:27019

09:55:44.356 [  Thread-0] in.dragonbra.javasteam.steam.discovery.SmartCMServerList - Marking /40.197.254.162:27019 - TCP as BAD

[bot#0] Disconnected from Steam!
```

**Comment by Longi94** [comment]
Weird, it works on my end (obviously). 40.197.254.162:27019 does not seem to be in the steam directory server list (https://api.steampowered.com/ISteamDirectory/GetCMList/v1?cellid=0), unless you are specifying a different cellid? Which IP are you connecting to when it works? Can you attach your `servers.bin` file somehow?

**Comment by exellian** [comment]
```[bot#0]` Connecting...
16:03:24.369 [  Thread-0] in.dragonbra.javasteam.steam.discovery.SmartCMServerList - Resolving server list
16:03:24.450 [  Thread-0] in.dragonbra.javasteam.steam.discovery.SmartCMServerList - Resolved 160 servers
16:03:24.460 [  Thread-0] in.dragonbra.javasteam.networking.steam3.TcpConnection - Connecting to /40.197.254.162:27018...
16:03:29.461 [  Thread-0] in.dragonbra.javasteam.networking.steam3.TcpConnection - java.net.SocketTimeoutException: connect timed out
Socket exception while completing connection request to /40.197.254.162:27018
16:03:29.461 [  Thread-0] in.dragonbra.javasteam.networking.steam3.TcpConnection - Timed out while connecting to /40.197.254.162:27018
	at java.net.DualStackPlainSocketImpl.waitForConnect(Native Method)
	at java.net.DualStackPlainSocketImpl.socketConnect(Unknown Source)
	at java.net.AbstractPlainSocketImpl.doConnect(Unknown Source)
	at java.net.AbstractPlainSocketImpl.connectToAddress(Unknown Source)
	at java.net.AbstractPlainSocketImpl.connect(Unknown Source)
	at java.net.PlainSocketImpl.connect(Unknown Source)
	at java.net.SocksSocketImpl.connect(Unknown Source)
	at java.net.Socket.connect(Unknown Source)
	at in.dragonbra.javasteam.networking.steam3.TcpConnection.connect(TcpConnection.java:114)
	at in.dragonbra.javasteam.networking.steam3.EnvelopeEncryptedConnection.connect(EnvelopeEncryptedConnection.java:193)
	at in.dragonbra.javasteam.networking.steam3.Connection.connect(Connection.java:62)
	at in.dragonbra.javasteam.steam.CMClient.connect(CMClient.java:166)
	at in.dragonbra.javasteam.steam.CMClient.connect(CMClient.java:137)
	at steam.SteamUser.run(SteamUser.java:118)
	at java.lang.Thread.run(Unknown Source)
16:03:29.462 [  Thread-0] in.dragonbra.javasteam.steam.discovery.SmartCMServerList - Marking /40.197.254.162:27018 - TCP as BAD
[bot#0] Disconnected from Steam!
```
And the generated servers.bin file when i get this error: https://drive.google.com/open?id=1f7uyV1shYsbyI3KJKvlYdNvk3jtmSVFq

**Comment by exellian** [comment]
And the generated servers.bin file when i delete it before i start the program and it works:
https://drive.google.com/open?id=18HcOLBd7xrXH186Zi21Wrf1GtmjifL4n
```
[bot#0] Connecting...
16:08:22.210 [  Thread-0] in.dragonbra.javasteam.steam.discovery.SmartCMServerList - Resolving server list
16:08:22.221 [  Thread-0] in.dragonbra.javasteam.steam.discovery.SmartCMServerList - Server list provider had no entries, will query SteamDirectory
16:08:22.802 [  Thread-0] in.dragonbra.javasteam.steam.discovery.SmartCMServerList - Resolved 200 servers
16:08:22.818 [  Thread-0] in.dragonbra.javasteam.networking.steam3.TcpConnection - Connecting to /162.254.197.40:27019...
16:08:22.868 [  Thread-0] in.dragonbra.javasteam.networking.steam3.TcpConnection - Connected to /162.254.197.40:27019
16:08:22.980 [TcpConnect] in.dragonbra.javasteam.networking.steam3.EnvelopeEncryptedConnection - Got encryption request. Universe: Public Protocol ver: 1
16:08:23.522 [TcpConnect] in.dragonbra.javasteam.networking.steam3.EnvelopeEncryptedConnection - Encryption result: OK
16:08:23.525 [TcpConnect] in.dragonbra.javasteam.steam.discovery.SmartCMServerList - Marking /162.254.197.40:27019 - TCP as GOOD
[bot#0] Connected to Steam!
16:08:23.593 [  Thread-0] in.dragonbra.javasteam.steam.CMClient - Sent -> EMsg: ClientLogon (Proto: true)
16:08:24.233 [TcpConnect] in.dragonbra.javasteam.steam.CMClient - <- Recv'd EMsg: Multi (1) (Proto: true)
16:08:24.238 [TcpConnect] in.dragonbra.javasteam.steam.CMClient - <- Recv'd EMsg: ClientServersAvailable (5501) (Proto: true)
16:08:24.238 [TcpConnect] in.dragonbra.javasteam.steam.CMClient - <- Recv'd EMsg: ClientServersAvailable (5501) (Proto: true)
16:08:24.238 [TcpConnect] in.dragonbra.javasteam.steam.CMClient - <- Recv'd EMsg: ClientServersAvailable (5501) (Proto: true)
16:08:24.239 [TcpConnect] in.dragonbra.javasteam.steam.CMClient - <- Recv'd EMsg: ClientServersAvailable (5501) (Proto: true)
16:08:24.239 [TcpConnect] in.dragonbra.javasteam.steam.CMClient - <- Recv'd EMsg: ClientServersAvailable (5501) (Proto: true)
16:08:24.239 [TcpConnect] in.dragonbra.javasteam.steam.CMClient - <- Recv'd EMsg: ClientLogOnResponse (751) (Proto: true)
16:08:24.243 [   Timer-0] in.dragonbra.javasteam.steam.CMClient - Sent -> EMsg: ClientHeartBeat (Proto: true)
[bot#0] Successfully logged on!
16:08:24.244 [TcpConnect] in.dragonbra.javasteam.steam.CMClient - <- Recv'd EMsg: ClientAccountInfo (768) (Proto: true)
16:08:24.246 [  Thread-0] in.dragonbra.javasteam.steam.CMClient - Sent -> EMsg: ClientGetNumberOfCurrentPlayersDP (Proto: true)
16:08:24.247 [TcpConnect] in.dragonbra.javasteam.steam.CMClient - <- Recv'd EMsg: ClientAccountInfo (768) (Proto: true)
16:08:24.247 [TcpConnect] in.dragonbra.javasteam.steam.CMClient - <- Recv'd EMsg: ClientEmailAddrInfo (5456) (Proto: true)
16:08:24.247 [TcpConnect] in.dragonbra.javasteam.steam.CMClient - <- Recv'd EMsg: ClientFriendsList (767) (Proto: true)
16:08:24.249 [  Thread-0] in.dragonbra.javasteam.steam.CMClient - Sent -> EMsg: ClientChangeStatus (Proto: true)
16:08:24.249 [  Thread-0] in.dragonbra.javasteam.steam.CMClient - Sent -> EMsg: ClientChangeStatus (Proto: true)
16:08:24.252 [TcpConnect] in.dragonbra.javasteam.steam.CMClient - Sent -> EMsg: ClientRequestFriendData (Proto: true)
16:08:24.253 [TcpConnect] in.dragonbra.javasteam.steam.CMClient - <- Recv'd EMsg: ClientFriendsGroupsList (5553) (Proto: true)
16:08:24.253 [TcpConnect] in.dragonbra.javasteam.steam.CMClient - <- Recv'd EMsg: ClientPlayerNicknameList (5587) (Proto: true)
16:08:24.254 [TcpConnect] in.dragonbra.javasteam.steam.CMClient - <- Recv'd EMsg: ClientLicenseList (780) (Proto: true)
16:08:24.259 [TcpConnect] in.dragonbra.javasteam.steam.CMClient - <- Recv'd EMsg: ClientUpdateGuestPassesList (798) (Proto: false)
16:08:24.259 [TcpConnect] in.dragonbra.javasteam.steam.CMClient - <- Recv'd EMsg: ClientWalletInfoUpdate (5528) (Proto: true)
16:08:24.262 [TcpConnect] in.dragonbra.javasteam.steam.CMClient - <- Recv'd EMsg: ClientGameConnectTokens (779) (Proto: true)
16:08:24.263 [TcpConnect] in.dragonbra.javasteam.steam.CMClient - <- Recv'd EMsg: ClientSessionToken (850) (Proto: true)
16:08:24.265 [TcpConnect] in.dragonbra.javasteam.steam.CMClient - <- Recv'd EMsg: ClientIsLimitedAccount (5430) (Proto: true)
16:08:24.265 [TcpConnect] in.dragonbra.javasteam.steam.CMClient - <- Recv'd EMsg: ClientCMList (783) (Proto: true)
16:08:24.273 [TcpConnect] in.dragonbra.javasteam.steam.CMClient - <- Recv'd EMsg: ClientServerList (880) (Proto: true)
16:08:24.277 [TcpConnect] in.dragonbra.javasteam.steam.CMClient - <- Recv'd EMsg: ClientRequestedClientStats (5480) (Proto: true)
16:08:24.277 [TcpConnect] in.dragonbra.javasteam.steam.CMClient - <- Recv'd EMsg: ClientServerList (880) (Proto: true)
16:08:24.278 [TcpConnect] in.dragonbra.javasteam.steam.CMClient - <- Recv'd EMsg: ClientVACBanStatus (782) (Proto: false)
16:08:24.278 [TcpConnect] in.dragonbra.javasteam.steam.CMClient - <- Recv'd EMsg: ClientUpdateMachineAuth (5537) (Proto: true)
16:08:24.482 [TcpConnect] in.dragonbra.javasteam.steam.CMClient - <- Recv'd EMsg: Multi (1) (Proto: true)
16:08:24.484 [TcpConnect] in.dragonbra.javasteam.steam.CMClient - <- Recv'd EMsg: ClientServersAvailable (5501) (Proto: true)
16:08:24.685 [TcpConnect] in.dragonbra.javasteam.steam.CMClient - <- Recv'd EMsg: Multi (1) (Proto: true)
16:08:24.685 [TcpConnect] in.dragonbra.javasteam.steam.CMClient - <- Recv'd EMsg: ClientGetNumberOfCurrentPlayersDPResponse (5593) (Proto: true)
[bot#0] value: 446143
16:08:24.789 [TcpConnect] in.dragonbra.javasteam.steam.CMClient - <- Recv'd EMsg: Multi (1) (Proto: true)
16:08:24.789 [TcpConnect] in.dragonbra.javasteam.steam.CMClient - <- Recv'd EMsg: ClientPersonaState (766) (Proto: true)
16:08:24.797 [TcpConnect] in.dragonbra.javasteam.steam.CMClient - <- Recv'd EMsg: ClientClanState (822) (Proto: true)
16:08:24.802 [TcpConnect] in.dragonbra.javasteam.steam.CMClient - <- Recv'd EMsg: ClientClanState (822) (Proto: true)
16:08:24.802 [TcpConnect] in.dragonbra.javasteam.steam.CMClient - <- Recv'd EMsg: ClientPersonaState (766) (Proto: true)
16:08:24.803 [TcpConnect] in.dragonbra.javasteam.steam.CMClient - <- Recv'd EMsg: ClientPersonaState (766) (Proto: true)
16:08:24.904 [TcpConnect] in.dragonbra.javasteam.steam.CMClient - <- Recv'd EMsg: Multi (1) (Proto: true)
16:08:24.905 [TcpConnect] in.dragonbra.javasteam.steam.CMClient - <- Recv'd EMsg: ClientPersonaState (766) (Proto: true)
16:08:24.908 [TcpConnect] in.dragonbra.javasteam.steam.CMClient - <- Recv'd EMsg: ClientPersonaState (766) (Proto: true)
16:08:24.909 [TcpConnect] in.dragonbra.javasteam.steam.CMClient - <- Recv'd EMsg: ClientPersonaState (766) (Proto: true)
16:08:24.911 [TcpConnect] in.dragonbra.javasteam.steam.CMClient - <- Recv'd EMsg: ClientPersonaState (766) (Proto: true)
16:08:24.912 [TcpConnect] in.dragonbra.javasteam.steam.CMClient - <- Recv'd EMsg: ClientPersonaState (766) (Proto: true)
16:08:24.915 [TcpConnect] in.dragonbra.javasteam.steam.CMClient - <- Recv'd EMsg: ClientPersonaState (766) (Proto: true)
16:08:24.916 [TcpConnect] in.dragonbra.javasteam.steam.CMClient - <- Recv'd EMsg: ClientPersonaState (766) (Proto: true)
16:08:24.916 [TcpConnect] in.dragonbra.javasteam.steam.CMClient - <- Recv'd EMsg: ClientPersonaState (766) (Proto: true)
16:08:24.917 [TcpConnect] in.dragonbra.javasteam.steam.CMClient - <- Recv'd EMsg: ClientPersonaState (766) (Proto: true)
16:08:24.918 [TcpConnect] in.dragonbra.javasteam.steam.CMClient - <- Recv'd EMsg: ClientPersonaState (766) (Proto: true)
16:08:24.919 [TcpConnect] in.dragonbra.javasteam.steam.CMClient - <- Recv'd EMsg: ClientPersonaState (766) (Proto: true)
16:08:24.920 [TcpConnect] in.dragonbra.javasteam.steam.CMClient - <- Recv'd EMsg: ClientPersonaState (766) (Proto: true)
16:08:24.922 [TcpConnect] in.dragonbra.javasteam.steam.CMClient - <- Recv'd EMsg: ClientPersonaState (766) (Proto: true)
16:08:25.525 [TcpConnect] in.dragonbra.javasteam.steam.CMClient - <- Recv'd EMsg: Multi (1) (Proto: true)
16:08:25.527 [TcpConnect] in.dragonbra.javasteam.steam.CMClient - <- Recv'd EMsg: ClientMarketingMessageUpdate2 (5510) (Proto: false)
```

**Comment by Longi94** [comment]
Looks like the IP is flipped, `162.254.197.40` -> `40.197.254.162`. Are you using the built in `FileServerListProvider` or a custom one?

**Comment by exellian** [comment]
Built in

**Comment by Longi94** [comment]
I can't reproduce this issue. I have no idea how and why would the IP flip like that, you might wanna contact me on discord for that.
